export const ADD_CONTACT = 'ADD_CONTACT';
export const DELETE_CONTACT = 'DELETE_CONTACT';
export const EDIT_CONTACT = 'EDIT_CONTACT';
export const GET_ALL_CONTACTS = 'GET_ALL_CONTACTS';
export const SET_FILTER_TEXT = 'SET_FILTER_TEXT';
export const REMOVE_ALL_CONTACTS = 'REMOVE_ALL_CONTACTS';
export const USER_AUTHENTICATED = 'USER_AUTHENTICATED';
export const USER_NOT_AUTHENTICATED = 'USER_NOT_AUTHENTICATED';
